[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maze-solver"
version = "1.0.0"

dependencies = [
    "networkx >= 3.0",
]

[project.scripts]
solve = "maze_solver.__main__:main"
